// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ljoieocugpdzhvdxkrcc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxqb2llb2N1Z3Bkemh2ZHhrcmNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwNjQ1NzgsImV4cCI6MjA1NjY0MDU3OH0.QbsoiVud0j6xKKDiTHXfDCeHW-pz4qiKS7UxheMXeBo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);